In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Load Heart Dataset (Online)
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data"

columns = [
    "age", "sex", "cp", "trestbps", "chol", "fbs",
    "restecg", "thalach", "exang", "oldpeak",
    "slope", "ca", "thal", "target"
]

df = pd.read_csv(url, header=None, names=columns, na_values="?")

# Remove missing values
df.dropna(inplace=True)

# Convert target to binary (0 = No Disease, 1 = Disease)
df["target"] = (df["target"] > 0).astype(int)

# Features and Target

X = df.drop("target", axis=1).values
y = df["target"].values.reshape(-1, 1)

# Normalize Features
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.3,
    random_state=42
)

# MLP Parameters
input_size = X_train.shape[1]
hidden_size = 5
output_size = 1

learning_rate = 0.1
epochs = 10

# Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Initialize Weights
np.random.seed(42)

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

# Training Loop
for epoch in range(epochs):

    # Forward Pass
    Z1 = np.dot(X_train, W1) + b1
    A1 = sigmoid(Z1)

    Z2 = np.dot(A1, W2) + b2
    A2 = sigmoid(Z2)

    # Loss
    loss = np.mean((y_train - A2) ** 2)

    # Backward Pass
    dA2 = A2 - y_train
    dZ2 = dA2 * sigmoid_derivative(A2)

    dW2 = np.dot(A1.T, dZ2)
    db2 = np.sum(dZ2, axis=0, keepdims=True)

    dA1 = np.dot(dZ2, W2.T)
    dZ1 = dA1 * sigmoid_derivative(A1)

    dW1 = np.dot(X_train.T, dZ1)
    db1 = np.sum(dZ1, axis=0, keepdims=True)

    # Update Parameters
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2

    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1

    # Print Each Epoch
    print(f"\nEpoch {epoch+1}/{epochs}")
    print("W1:", W1.round(4))
    print("b1:", b1.round(4))
    print("W2:", W2.round(4))
    print("b2:", b2.round(4))
    print("Loss:", round(loss, 4))

# Testing
Z1_test = np.dot(X_test, W1) + b1
A1_test = sigmoid(Z1_test)

Z2_test = np.dot(A1_test, W2) + b2
A2_test = sigmoid(Z2_test)

preds = (A2_test > 0.5).astype(int)

accuracy = np.mean(preds == y_test)

print("\n✅ Final Test Accuracy: {:.2f}%".format(accuracy * 100))


Epoch 1/10
W1: [[ 0.3987 -0.1334  0.5609  1.5091 -0.1928]
 [-0.2696  1.581   0.7104 -0.476   0.5745]
 [-0.5583 -0.4606  0.1498 -1.9274 -1.6855]
 [-0.6226 -1.0097  0.2567 -0.9161 -1.3854]
 [ 1.4096 -0.223   0.0186 -1.4313 -0.5197]
 [ 0.0664 -1.1483  0.3347 -0.6043 -0.269 ]
 [-0.6657  1.8553 -0.0861 -1.0661  0.8583]
 [-1.3807  0.2168 -2.1023 -1.3451  0.2696]
 [ 0.7538  0.1705 -0.1033 -0.3032 -1.4837]
 [-0.7113 -0.461   1.0602  0.3416 -1.7632]
 [ 0.3014 -0.3839 -0.6977  0.6048  1.0447]
 [ 0.9726 -0.841  -0.2787  0.3311  0.9576]
 [-0.403  -0.189  -1.0499 -1.195   0.7859]]
b1: [[-0.2139  0.0107 -0.1902 -0.0264  0.0959]]
W2: [[ 1.1223]
 [-0.5486]
 [ 0.6669]
 [ 0.2727]
 [-0.8591]]
b2: [[-0.8163]]
Loss: 0.2794

Epoch 2/10
W1: [[ 0.4929 -0.1748  0.6142  1.5099 -0.2543]
 [-0.0908  1.4996  0.8179 -0.4697  0.4534]
 [-0.4013 -0.5301  0.239  -1.9262 -1.7864]
 [-0.5612 -1.0379  0.2922 -0.9153 -1.4263]
 [ 1.4592 -0.2446  0.0454 -1.4309 -0.5503]
 [ 0.0868 -1.1567  0.3443 -0.6047 -0.2798]
 [-0.5603  1.